In [2]:
# dependencies
import pandas as pd

In [3]:
# get all the csv filepaths and create a list of files
bikedata_2019_01 = "data/JC-201901-citibike-tripdata.csv"
bikedata_2019_02 = "data/JC-201902-citibike-tripdata.csv"
bikedata_2019_03 = "data/JC-201903-citibike-tripdata.csv"
bikedata_2019_04 = "data/JC-201904-citibike-tripdata.csv"
bikedata_2019_05 = "data/JC-201905-citibike-tripdata.csv"
bikedata_2019_06 = "data/JC-201906-citibike-tripdata.csv"
bikedata_2019_07 = "data/JC-201907-citibike-tripdata.csv"
bikedata_2019_08 = "data/JC-201908-citibike-tripdata.csv"
bikedata_2019_09 = "data/JC-201909-citibike-tripdata.csv"
bikedata_2019_10 = "data/JC-201910-citibike-tripdata.csv"
bikedata_2019_11 = "data/JC-201911-citibike-tripdata.csv"
bikedata_2019_12 = "data/JC-201912-citibike-tripdata.csv"

all_files = [bikedata_2019_01,bikedata_2019_02,bikedata_2019_03,bikedata_2019_04,bikedata_2019_05,bikedata_2019_06,
             bikedata_2019_07, bikedata_2019_08,bikedata_2019_09,bikedata_2019_10,bikedata_2019_11,bikedata_2019_12]

In [4]:
# create empty list to add dataframes to
bikedata_list = []

# for loop to go through each file and read into dataframe, then append to the new list
for file in all_files:
    bikedata_list.append(pd.read_csv(file))

# concatenate the list of dataframes to a single dataframe
bikedata_2019 = pd.concat(bikedata_list, sort=False)
bikedata_2019

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19723,283,2019-12-31 23:12:18.5480,2019-12-31 23:17:01.8740,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29245,Customer,1990,1
19724,267,2019-12-31 23:19:03.5840,2019-12-31 23:23:30.6640,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26153,Subscriber,1989,1
19725,379,2019-12-31 23:19:06.5830,2019-12-31 23:25:25.7970,3209,Brunswick St,40.724176,-74.050656,3185,City Hall,40.717733,-74.043845,26276,Subscriber,1984,1
19726,188,2019-12-31 23:24:00.2630,2019-12-31 23:27:09.0400,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,29461,Subscriber,1987,1
19727,326,2019-12-31 23:45:20.9780,2019-12-31 23:50:47.7490,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29123,Subscriber,1988,1

In [5]:
bikedata_2019.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [6]:
# clean the df to have only the data with birth year over 1919 (under 100 years old)
bikedata_df = bikedata_2019.loc[bikedata_2019["birth year"] > 1919, :]

# reset index
bikedata_df = bikedata_df.reset_index(drop = True)

In [7]:
bikedata_df.describe()

,tripduration,start station id,start station latitude,start station longitude,end station id,end station latitude,end station longitude,bikeid,birth year,gender
count,4.047500e+05,404750.000000,404750.000000,404750.000000,404750.000000,404750.000000,404750.000000,404750.000000,404750.000000,404750.000000
mean,7.260156e+02,3294.027506,40.722723,-74.046335,3292.234174,40.722329,-74.045795,28465.450883,1981.460917,1.162747
std,9.787606e+03,171.028774,0.007038,0.010872,180.834746,0.006886,0.010830,1654.274911,10.068458,0.515796
min,6.100000e+01,3183.000000,40.709651,-74.083639,116.000000,40.695065,-74.083639,14792.000000,1940.000000,0.000000
25%,2.330000e+02,3195.000000,40.718355,-74.050444,3192.000000,40.718355,-74.050389,26286.000000,1975.000000,1.000000
50%,3.450000e+02,3210.000000,40.721525,-74.043845,3207.000000,40.721124,-74.043117,29284.000000,1984.000000,1.000000
75%,5.800000e+02,3276.000000,40.727224,-74.038051,3276.000000,40.727224,-74.038051,29536.000000,1989.000000,1.000000
max,2.566420e+06,3792.000000,40.748716,-74.032108,3792.000000,40.814326,-73.932077,41913.000000,2003.000000,2.000000

In [6]:
# output the final dataframe to a csv file for using in tableau

bikedata_df.to_csv("data/bikedata_2019.csv", index=False)